### ISSUE TITLE
Missing constructors for AiNode

### ISSUE THREAD

**Issue by phtaylor** [tadevelopment/fabric2arnold#3]
We should be able to construct new AtNodes by calling AiNode();

e.g. here is sample code from the docs. 

```
AtNode *mymesh = AiNode("polymesh");
AiNodeDeclare(mymesh, "bar", "constant BOOL");
AiNodeDeclare(mymesh, "heatmap", "constant ARRAY RGB");
```

here is the docs page for the missing method. 
https://trac.solidangle.com/arnoldpedia/chrome/site/Arnold-4.1.3.3/doc/api/group__ai__nodes.html#gae293ec14ca3ecc65e630ee01209d3a23

Without this method it is impossible to generate Arnold scenes for export or rendering. (which I need to do)

**Comment by phtaylor** [comment]
https://github.com/tadevelopment/fabric2arnold/blob/Develop_2.0/Tests/test2_Sphere.kl

```
  // create a sphere
  AtNode sphere = AiNode("sphere");
  AiNodeSetStr(sphere, "name", "mysphere");
  AiNodeSetFlt(sphere, "radius", 5.0);
```

I am pretty sure the tests are not passing, because the method 'AiNode(String)' is not found anywhere in the API. 

This is where I would expect it to be
https://github.com/tadevelopment/fabric2arnold/blob/Develop_2.0/GenKL/ai_nodes.kl

**Comment by FrozenKiwi** [comment]
The Arnold API at the moment (4.10 or something near) is transitioning from const char\* arguments to AtString, with both versions of the function arguments there, but the const char\* version deprecated.

The AtString versions all contain the AtString postfix to the function name.  The auto-wrapper does not wrap deprecated functions (it seems a bad idea to have a deprecated function in an essentially brand-new API) so we only have the AtString versions exposed.  In ai_nodes, there is a function definition AiNodeAtString, this is the function you are looking for.

Because its very annoying to add AtString to every function when calling it, I've added in a renaming layer in the Fabric2ArnoldWrappers extension, so by importing this extension instead of Fabric2Arnold you will have a much nicer interface and can just call the natural fn name, 

```
AiNode("mesh") // maps to AiNodeAtString
```

The purpose of this extension is to make the extensions more KL friendly, and its always recommended to use the wrapper layer over the 'raw' C++-style interface when working in KL.

**Comment by caron** [comment]
Sorry for being nosy but I thought I might be able to provide some more insight. Arnold guys are rolling their own string type, AtString, they added this to the public API in 4.2.6...

https://trac.solidangle.com/arnoldpedia/chrome/site/Arnold-4.2.6.0/doc/api/group__ai__nodes.html

From the dev, Thiago

> The plan is to get rid of the older non-AtString functions as soon as we are allowed to break the API (probably Arnold 5.0).  This way there won't be any debate about which version to call.  If you don't care that much about speed, you can just create a new AtString each time you call the function:

So, I think Stephen's wrapper is the way to go and avoid ever using directly the AtString postfix versions.

**Comment by phtaylor** [comment]
ok, thanks Steven
